// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBogl_0iyzOqJS7C0bcfetJgCPcbj4ZATY',
    appId: '1:688777327471:web:a8d10015b173afb92f6e9a',
    messagingSenderId: '688777327471',
    projectId: 'oil-bussiness',
    authDomain: 'oil-bussiness.firebaseapp.com',
    storageBucket: 'oil-bussiness.firebasestorage.app',
    measurementId: 'G-CK9CTC0772',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUJxaYYrDmbxxOgGOg6k9tJZQ0whv7RQ',
    appId: '1:688777327471:android:2473e9e9be37717e2f6e9a',
    messagingSenderId: '688777327471',
    projectId: 'oil-bussiness',
    storageBucket: 'oil-bussiness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MHpDSIFComq2SX60axRX3mOUYPLwNkM',
    appId: '1:688777327471:ios:89544c05fecd42a52f6e9a',
    messagingSenderId: '688777327471',
    projectId: 'oil-bussiness',
    storageBucket: 'oil-bussiness.firebasestorage.app',
    iosBundleId: 'com.example.oilBussiness',
  );
}
